version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: word-puzzle
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
        expose:
            - "9000"

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        volumes:
            - ./docker-compose/nginx:/etc/nginx/conf.d/
            - .:/var/www
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:latest
        container_name: laravel-postgres
        environment:
            POSTGRES_USER: andrejkozlina
            POSTGRES_PASSWORD: andra
            POSTGRES_DB: wordpuzzle
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel
networks:
    laravel:
        driver: bridge

volumes:
    pg_data:


